namespace Manifold.GfzCli;

/// <summary>
///     List of all possible actions in this CLI program.
/// </summary>
public enum CliActionID
{
    none,
    list,
    usage,

    arc_unpack,
    arc_pack,
    asset_custom_mipmap_gxtex,
    asset_generate_library,
    asset_gmaref_to_gma,
    asset_image_to_gxtex,
    asset_tpl_unpack,
    asset_tplref_pack,
    cam_livecamstage_from_tsv,
    cam_livecamstage_to_tsv,
    cardata_from_tsv,
    cardata_to_tsv,
    colicourse_patch_fog,
    colicourse_patch_object_render_flags,
    iso_extract,
    iso_extract_files,
    iso_extract_system,
    encode_bytes_to_shift_jis,
    encode_windows_to_shift_jis,
    emblem_gci_from_image,
    emblem_gci_to_image,
    emblems_bin_from_images,
    emblems_bin_to_images,
    fmi_from_plaintext,
    fmi_to_plaintext,
    fzrel_clear_all_course_names,
    fzrel_clear_all_venue_names,
    fzrel_clear_unused_course_names,
    fzrel_clear_unused_venue_names,
    fzrel_decrypt,
    fzrel_encrypt,
    fzrel_set_bgm,
    fzrel_set_bgmfl,
    fzrel_set_bgm_bgmfl,
    fzrel_set_cardata,
    fzrel_set_course_difficulty,
    fzrel_set_course_name,
    fzrel_set_cup_course,
    fzrel_set_machine_rating,
    fzrel_set_max_speed,
    fzrel_set_course_venue,
    fzrel_set_venue_name,
    fzrel_community_mod1,
    gci_extract_ghost,
    gma_patch_submesh_render_flags,
    io_gma,
    io_scene,
    io_scene_null_comment,
    io_tpl,
    log_gma_all,
    log_stage_all,
    log_stage_track_keyables,
    lz_compress,
    lz_decompress,
}
